export const categories = [
  "technology",
  "lifestyle",
  "education",
  "entertainment",
  "food",
  "personal development",
  "finance",
  "sports & fitness",
  "art",
  "environment",
  "science",
  "gaming",
  "parenting & family",
  "culture",
  "history",
  "literature",
  "books",
  "politics",
];
